/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./src/components/403.vue')['default']
    Bullet: typeof import('./src/components/bullet.vue')['default']
    BulletLoop: typeof import('./src/components/bulletLoop/bulletLoop.vue')['default']
    Demo: typeof import('./src/components/waterMark/demo.vue')['default']
    FileUpload: typeof import('./src/components/largeFileUpload/fileUpload.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LazyLoad: typeof import('./src/components/lazyLoad/lazyLoad.vue')['default']
    Mock: typeof import('./src/components/mock/mock.vue')['default']
    MutilDialog: typeof import('./src/components/mutilDialog/mutilDialog.vue')['default']
    PullLoad: typeof import('./src/components/pullLoad/pullLoad.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/switch/switch.vue')['default']
    VirtualList: typeof import('./src/components/virtualList/virtualList.vue')['default']
  }
}
